#!/bin/sh

########################################################################
# Shell agnostic path setup
########################################################################

export PATH=$PATH:.
export PATH=$PATH:~/bin
export PATH=$PATH:~/dotfiles/scripts
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:~/adr-tools/src
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="$GOENV_ROOT/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
